---
- hosts: 198.18.134.49
  remote_user: root
  become: yes
  #sudo: yes
  tasks:
    # - name: install apache2
    #  yum: name=httpd update_cache=yes state=latest

    - name: Install apache packages
      yum:
        name: httpd
        state: present
    - name: ensure httpd is running
      service:
        name: httpd
        # become: yes
        # become_user: demouser
        state: started
    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Restart the firewalld service to load in the firewall changes
      service:
        name: firewalld
        state: restarted
    - name: Copying the demo file
      template: src=/etc/ansible/index.html dest=/var/www/html
        owner=root group=demouser mode=0644
- hosts: 198.18.134.50
  remote_user: root
  become: yes
  #sudo: yes
  tasks:
    # - name: install apache2
    #  yum: name=httpd update_cache=yes state=latest

    - name: Install apache packages
      yum:
        name: httpd
        state: present
    - name: ensure httpd is running
      service:
        name: httpd
        # become: yes
        # become_user: demouser
        state: started
    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Restart the firewalld service to load in the firewall changes
      service:
        name: firewalld
        state: restarted
    - name: Copying the demo file
      template: src=/etc/ansible/index.html dest=/var/www/html
        owner=root group=demouser mode=0644
